/**
 * assets_manifest.js
 * Automatically generated by generate_manifest.js
 */

export const ASSET_MANIFEST = {
    "1": [
        {
            "name": "a fucking flower",
            "image": "personagens/1/A_Fucking_Flower.svg",
            "sound": "personagens/1/A_Fucking_Flower.wav",
            "color": "#1f2937"
        },
        {
            "name": "clukr",
            "image": "personagens/1/Clukr.svg",
            "sound": "personagens/1/Clukr.wav",
            "color": "#1f2937"
        },
        {
            "name": "durple",
            "image": "personagens/1/Durple.svg",
            "sound": "personagens/1/Durple.wav",
            "color": "#1f2937"
        },
        {
            "name": "el cool p",
            "image": "personagens/1/El_Cool_P.svg",
            "sound": "personagens/1/El_Cool_P.ogg",
            "color": "#1f2937"
        },
        {
            "name": "empty polo",
            "image": "personagens/1/Empty_Polo.svg",
            "sound": "personagens/1/Empty_Polo.mp3",
            "color": "#1f2937"
        },
        {
            "name": "fun bot",
            "image": "personagens/1/Fun_Bot.svg",
            "sound": "personagens/1/Fun_Bot.mp3",
            "color": "#1f2937"
        },
        {
            "name": "garnold",
            "image": "personagens/1/Garnold.svg",
            "sound": "personagens/1/Garnold.wav",
            "color": "#1f2937"
        },
        {
            "name": "gray",
            "image": "personagens/1/Gray.svg",
            "sound": "personagens/1/Gray.wav",
            "color": "#1f2937"
        },
        {
            "name": "jevin",
            "image": "personagens/1/Jevin.svg",
            "sound": "personagens/1/Jevin.wav",
            "color": "#1f2937"
        },
        {
            "name": "mr fun computer",
            "image": "personagens/1/Mr_Fun_Computer.svg",
            "sound": "personagens/1/Mr_Fun_Computer.wav",
            "color": "#1f2937"
        },
        {
            "name": "mr sun",
            "image": "personagens/1/Mr_Sun.svg",
            "sound": "personagens/1/Mr_Sun.wav",
            "color": "#1f2937"
        },
        {
            "name": "mr tree",
            "image": "personagens/1/Mr_Tree.svg",
            "sound": "personagens/1/Mr_Tree.wav",
            "color": "#1f2937"
        },
        {
            "name": "owakcx",
            "image": "personagens/1/OWAKCX.svg",
            "sound": "personagens/1/OWAKCX.wav",
            "color": "#1f2937"
        },
        {
            "name": "oren",
            "image": "personagens/1/Oren.svg",
            "sound": "personagens/1/Oren.wav",
            "color": "#1f2937"
        },
        {
            "name": "pinki",
            "image": "personagens/1/Pinki.svg",
            "sound": "personagens/1/Pinki.wav",
            "color": "#1f2937"
        },
        {
            "name": "raddy",
            "image": "personagens/1/Raddy.svg",
            "sound": "personagens/1/Raddy.wav",
            "color": "#1f2937"
        },
        {
            "name": "rebel",
            "image": "personagens/1/Rebel.svg",
            "sound": "personagens/1/Rebel.mp3",
            "color": "#1f2937"
        },
        {
            "name": "simon",
            "image": "personagens/1/Simon.svg",
            "sound": "personagens/1/Simon.wav",
            "color": "#1f2937"
        },
        {
            "name": "sky",
            "image": "personagens/1/Sky.svg",
            "sound": "personagens/1/Sky.wav",
            "color": "#1f2937"
        },
        {
            "name": "tunner",
            "image": "personagens/1/Tunner.svg",
            "sound": "personagens/1/Tunner.wav",
            "color": "#1f2937"
        },
        {
            "name": "vineria",
            "image": "personagens/1/Vineria.svg",
            "sound": "personagens/1/Vineria.wav",
            "color": "#1f2937"
        },
        {
            "name": "wenda",
            "image": "personagens/1/Wenda.svg",
            "sound": "personagens/1/Wenda.wav",
            "color": "#1f2937"
        },
        {
            "name": "brud",
            "image": "personagens/1/brud.svg",
            "sound": "personagens/1/brud.wav",
            "color": "#1f2937"
        }
    ],
    "2": [
        {
            "name": "black",
            "image": "personagens/2/Black.svg",
            "sound": "personagens/2/Black.wav",
            "color": "#1f2937"
        },
        {
            "name": "cube",
            "image": "personagens/2/Cube.svg",
            "sound": "personagens/2/Cube.wav",
            "color": "#1f2937"
        },
        {
            "name": "darius",
            "image": "personagens/2/Darius.svg",
            "sound": "personagens/2/Darius.wav",
            "color": "#1f2937"
        },
        {
            "name": "dr theodore",
            "image": "personagens/2/Dr_Theodore.svg",
            "sound": "personagens/2/Dr_Theodore.mp3",
            "color": "#1f2937"
        },
        {
            "name": "executive",
            "image": "personagens/2/Executive.svg",
            "sound": "personagens/2/Executive.mp3",
            "color": "#1f2937"
        },
        {
            "name": "fanon wenda",
            "image": "personagens/2/Fanon_Wenda.svg",
            "sound": "personagens/2/Fanon_Wenda.wav",
            "color": "#1f2937"
        },
        {
            "name": "geno",
            "image": "personagens/2/Geno.svg",
            "sound": "personagens/2/Geno.wav",
            "color": "#1f2937"
        },
        {
            "name": "geo",
            "image": "personagens/2/Geo.svg",
            "sound": "personagens/2/Geo.wav",
            "color": "#1f2937"
        },
        {
            "name": "imperfection",
            "image": "personagens/2/Imperfection.svg",
            "sound": "personagens/2/Imperfection.wav",
            "color": "#1f2937"
        },
        {
            "name": "kaski",
            "image": "personagens/2/Kaski.svg",
            "sound": "personagens/2/Kaski.wav",
            "color": "#1f2937"
        },
        {
            "name": "lario",
            "image": "personagens/2/Lario.svg",
            "sound": "personagens/2/Lario.wav",
            "color": "#1f2937"
        },
        {
            "name": "lobotomy man",
            "image": "personagens/2/Lobotomy_Man.svg",
            "sound": "personagens/2/Lobotomy_Man.mp3",
            "color": "#1f2937"
        },
        {
            "name": "locke",
            "image": "personagens/2/Locke.svg",
            "sound": "personagens/2/Locke.wav",
            "color": "#1f2937"
        },
        {
            "name": "mack",
            "image": "personagens/2/Mack.svg",
            "sound": "personagens/2/Mack.wav",
            "color": "#1f2937"
        },
        {
            "name": "proop guy",
            "image": "personagens/2/Proop_Guy.svg",
            "sound": "personagens/2/Proop_Guy.wav",
            "color": "#1f2937"
        },
        {
            "name": "qipqqtppsgskkskk",
            "image": "personagens/2/Qipqqtppsgskkskk.svg",
            "sound": "personagens/2/Qipqqtppsgskkskk.wav",
            "color": "#1f2937"
        },
        {
            "name": "rose",
            "image": "personagens/2/Rose.svg",
            "sound": "personagens/2/Rose.wav",
            "color": "#1f2937"
        }
    ]
};

