const fs = require('fs');
const path = require('path');

const allowedImageExtensions = ['.svg']; // Strict SVG only as requested
const audioExtensions = ['.wav', '.mp3', '.ogg'];
const rootDir = '/Users/persivalballeste/Documents/Private/sprunki_app/sprunki_incredibox_game/personagens';

function scanDir(phase) {
    const dir = path.join(rootDir, phase);
    if (!fs.existsSync(dir)) return [];

    const files = fs.readdirSync(dir);
    const chars = {};

    files.forEach(file => {
        const ext = path.extname(file).toLowerCase();
        // Handle names with multiple dots properly if needed, but standard extname is fine for .svg/.wav
        const name = path.basename(file, ext);

        if (name.startsWith('.')) return;

        // Normalize key to lowercase for easier matching with IDs
        const key = name.toLowerCase();

        if (!chars[key]) chars[key] = {};

        if (allowedImageExtensions.includes(ext)) {
            chars[key].image = `personagens/${phase}/${file}`;
        } else if (audioExtensions.includes(ext)) {
            chars[key].sound = `personagens/${phase}/${file}`;
        }
    });

    return Object.entries(chars)
        .filter(([_, data]) => data.image && data.sound)
        .map(([name, data]) => ({
            name: name.replace(/_/g, ' '),
            image: data.image,
            sound: data.sound,
            color: '#1f2937' // Default color
        }));
}

const manifest = {
    '1': scanDir('1'),
    '2': scanDir('2')
};

const output = `/**
 * assets_manifest.js
 * Automatically generated by generate_manifest.js
 */

export const ASSET_MANIFEST = ${JSON.stringify(manifest, null, 4)};
`;

console.log(output);
